### ISSUE TITLE
Error CS0411 in TypeInference.CreateDxDataGrid

### ISSUE THREAD

**Issue by johnholliday** [DevExpress/XPO#31]
The Index.razor page fails to build with the following error:

**Error CS0411**	The type arguments for method 'TypeInference.CreateDxDataGrid_0<T>(RenderTreeBuilder, int, int, IEnumerable<T>, int, string, int, object, int, int, int, bool, int, Action<T>, int, Action<T, Dictionary<string, object>>, int, Action<Dictionary<string, object>>, int, RenderFragment)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**..\Debug\netcoreapp3.1\Razor\Pages\Index.razor.g.cs	116**

**Comment by pavelstaro** [comment]
Try return **Task<IEnumerable<DTO>>** instead of **Task<List<DTO>>** from your service inside DataAsync tag

`<DxDataGrid DataAsync="@AcrFlowFacade.GetListAsync"
            PageSize="10">
    <DxDataGridColumn Field="@nameof(AcrFlowTableDTO.Id)" />
</DxDataGrid>`

It helps for me.

**Comment by maksimkarpenko** [comment]
@johnholliday, @pavelstaro - we cannot reproduce this error with the latest Visual Studio version and .NET Core SDK 3.1. Please try this code with the latest version.

**Comment by jluoPT** [comment]
I had the same error, with core 3.1, VS 2019

**Comment by maksimkarpenko** [comment]
@jluoPT, would you please submit a ticket in our [Support Center](https://supportcenter.devexpress.com/ticket/list) so that we can discuss this issue further?

**Comment by Thomas5x01** [comment]
Hi,
I just ran into the same error.
In my case it helped adding System.Threading.CancellationToken cancellationToken as a parameter in my DataService.GetAllAsnyc(...) method.
More generalized my advice would be: compare all the parameter types passed to TypeInference.CreateDxDataGrid_0. If a parameter type does not match Error CS0411 occurs. Because the type parameters are not used explicitly, there is no error message telling which parameter type is wrong.

HTH

**Comment by dvangsne** [comment]
I'm getting the same error just working through this example: https://www.youtube.com/watch?v=v_ZMMGTlHhw
