### ISSUE TITLE
IS XPO no longer getting updates.

### ISSUE THREAD

**Issue by BicycleMark** [DevExpress/XPO#65]
I see there are very few updates is the last couple of years is this now a retired project?

**Comment by dennis-garavsky** [comment]
@BicycleMark : This repository contains only a few popular demo samples, which do not require much changes, because API is quite stable. 

DevExpress XPO ORM itself is an active project that regularly gets updates through https://www.nuget.org/packages/DevExpress.Xpo/ and https://nuget.devexpress.com/. For instance, you can see the list of the resolved issues in the last year in [the DevExpress version history](https://supportcenter.devexpress.com/versionhistory?platformsWithProducts=d76afe22-512e-45a3-ad81-7b245352e111%3A9eda7be2-8f23-467b-bb4e-9d546db79c87&startBuildName=20.2.1&endBuildName=22.1.1&buildsMode=Range&hasPlatformsWithProducts=false).

Our free XPO ORM is also at the core of many commercial DevExpress products like [Cross-Platform .NET App UI (XAF)](https://www.devexpress.com/products/net/application_framework/), [.NET Role-based Access Control API](https://www.devexpress.com/products/net/application_framework/security.xml), Dashboards, Reporting, etc. with thousands of users - so it is not going to be retired soon anyway :-)
